version: "2.0"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    image: statechain-server
    ports:
      - '5000:5000'
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    command: ["./wait-for-it.sh", "db:5432", "--", "yarn", "run", "start"]
  test:
    build:
      context: .
    depends_on:
      - db
      - api
    environment:
      CI: true
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    command: ["./wait-for-it.sh", "db:5432", "--", "yarn", "run", "test"]